export const configProperties = [
  'disable_simulation',

  'simulation_decay',
  'simulation_gravity',
  'simulation_center',
  'simulation_repulsion',
  'simulation_repulsion_theta',
  'simulation_repulsion_quadtree_levels',
  'simulation_link_spring',
  'simulation_link_distance',
  'simulation_link_dist_random_variation_range',
  'simulation_repulsion_from_mouse',
  'simulation_friction',
  'simulation_cluster',

  'background_color',
  'space_size',
  'point_color',
  'point_greyout_opacity',
  'point_size',
  'point_size_scale',
  'hovered_point_cursor',
  'render_hovered_point_ring',
  'hovered_point_ring_color',
  'focused_point_ring_color',
  'focused_point_index',
  'render_links',
  'link_color',
  'link_greyout_opacity',
  'link_width',
  'link_width_scale',
  'curved_links',
  'curved_link_segments',
  'curved_link_weight',
  'curved_link_control_point_distance',
  'link_arrows',
  'link_arrows_size_scale',
  'link_visibility_distance_range',
  'link_visibility_min_transparency',
  'use_quadtree',
  'show_FPS_monitor',
  'pixel_ratio',
  'scale_points_on_zoom',
  'initial_zoom_level',
  'disable_zoom',
  'enable_drag',
  'fit_view_on_init',
  'fit_view_delay',
  'fit_view_padding',
  'fit_view_duration',
  'fit_view_by_points_in_rect',
  'random_seed',
  'point_sampling_distance',

  'point_id_by',
  'point_index_by',
  'point_color_by',
  'point_color_palette',
  'point_color_by_map',
  'point_color_strategy',
  'point_size_by',
  'point_size_range',
  'point_size_strategy',
  'point_label_by',
  'point_label_weight_by',
  'point_x_by',
  'point_y_by',
  'point_cluster_by',
  'point_cluster_strength_by',
  'point_include_columns',

  'link_source_by',
  'link_source_index_by',
  'link_target_by',
  'link_target_index_by',
  'link_color_by',
  'link_width_by',
  'link_arrow_by',
  'link_strength_by',
  'link_strength_range',
  'link_include_columns',

  'show_labels',
  'show_dynamic_labels',
  'show_top_labels',
  'show_top_labels_limit',
  'show_top_labels_by',
  'show_labels_for',
  'static_label_weight',
  'dynamic_label_weight',
  'label_margin',

  // TODO: add padding when it will be as a array of numbers
  // 'label_padding',

  // 🤷‍♀️ Should we implement Custom Labels into the widget?
  // 'custom_labels',

  'show_hovered_point_label',

  'point_timeline_by',

]
